---
new_page_extension: md
auto_deploy: false
admin_path: "/admin"
webhook_url: 
sections:
- type: directory
  path: projects
  label: Projects
  create: documents
  match: "**/*.md"
  templates:
  - project
- type: directory
  path: journal
  label: Journal
  create: documents
  match: "**/*.md"
  templates:
  - journal
- type: directory
  path: data/authors
  label: Authors
  create: documents
  match: "**/*.json"
  new_doc_ext: json
  templates:
  - author
- type: document
  path: data/theme.json
  label: Theme config
upload_dir: uploads
public_path: "/uploads"
front_matter_path: "../uploads"
use_front_matter_path: true
file_template: ":filename:"
build:
  publish_command: gridsome build
  output_directory: dist
