---
label: Project
hide_body: false
is_partial: false
fields:
- type: file
  name: thumbnail
  label: Thumbnail
  description: This will only show up on the front page
- type: text
  name: title
  label: Title
  config:
    required: true
- type: datetime
  name: date
  label: Date
  config:
    required: true
- type: text
  name: year
  label: Year
  config:
    required: true
- type: tag_list
  name: categories
  label: Categories
pages:
- projects/chelsea-landmark.md
