---
label: Theme configuration
hide_body: true
is_partial: false
fields:
- type: file
  name: logo
  label: Logo
- name: footer
  label: Footer text
  type: text
  hidden: false
  default: ''
- type: boolean
  name: dark_mode
  label: Dark mode
